const API="/api";let players=[],kits=[],active=null,matches=[];
const $=id=>document.getElementById(id);const text=(id,v)=>{const e=$(id);if(e)e.textContent=v??"—"};const show=(id,on=true)=>$(id)?.classList.toggle("open",on);
async function api(path,opt={}){const r=await fetch(API+path,{headers:{"content-type":"application/json",...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed ("+r.status+")");return d}
function saveLocal(){if(active)localStorage.setItem("cribActivePlayer",active.id)}
function rank(r){return r>=3000?"Radiant":r>=2600?"Diamond":r>=2200?"Emerald":r>=1800?"Ruby":r>=1400?"Sapphire":r>=1000?"Gold":r>=700?"Silver":r>=400?"Bronze":"Unranked"}
function renderPlayers(){const s=$("activePlayerSelect");if(s){s.innerHTML=players.map(p=>`<option value="${p.id}">${p.displayName} · ${p.rp} RP</option>`).join("");if(active)s.value=active.id}const t=$("playersTableBody");if(t)t.innerHTML=players.map(p=>`<tr><td><b>${p.displayName}</b><br><span class="muted">@${p.username}</span></td><td>${rank(p.rp)}</td><td>${p.rp}</td><td>${p.wins}-${p.losses}</td><td>${p.winstreak}</td><td><button class="soft-btn" onclick="window.selectPlayer('${p.id}')">Open</button></td></tr>`).join("")}
function render(){if(!active)return;const p=active;const wr=p.wins+p.losses?(p.wins/(p.wins+p.losses)*100).toFixed(1):"0.0",kd=p.deaths?p.kills/p.deaths:p.kills;const r=rank(p.rp);["sideName","profileDisplayName"].forEach(x=>text(x,p.displayName));text("sideRank",r);text("profileUsername","@"+p.username);text("currentRankName",r);text("currentRankRP",p.rp);text("dashboardWins",p.wins);text("dashboardWinRate",wr+"%");text("dashboardKD",Number(kd).toFixed(2));text("profileRP",p.rp);text("profilePeakRP",p.peakRP);text("profileWins",p.wins);text("profileWinsLosses",p.wins+" / "+p.losses);text("profileWinRate",wr+"%");text("profileGames",p.wins+p.losses);text("profileMMR",p.mmr);text("profileLateELO",p.lateElo);text("profileCribRating",p.cribRating);text("profileBedStreak",p.winstreak);text("profileBestBedStreak",p.bestStreak);text("profileKills",p.kills);text("profileDeaths",p.deaths);text("profileKD",Number(kd).toFixed(2));text("profileBeds",p.beds);text("profileWinstreak",p.winstreak);text("profileBestStreak",p.bestStreak);text("rankTitle",r);text("rankSub",p.rp+" RP");text("currentRPValue",p.rp);text("quickWinstreak",p.winstreak);text("quickPeakRP",p.peakRP);renderPlayers()}
function openPage(name){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(name+"-page")?.classList.add("active");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.page===name))}
async function refresh(){const [a,b]=await Promise.all([api("/players"),api("/kits")]);players=a.players;kits=b.kits;active=players.find(p=>p.id===localStorage.getItem("cribActivePlayer"))||players[0]||null;render();populateKits()}
function populateKits(){["scrimKitSelect","winstreakOpponentKitSelect","mapModifierKit","compareKitA","compareKitB"].forEach(id=>{const e=$(id);if(e)e.innerHTML=kits.map(k=>`<option value="${k.name}">${k.name}</option>`).join("")})}
window.selectPlayer=async id=>{active=players.find(p=>p.id===id);saveLocal();render();openPage("dashboard")}
async function createPlayer(){const username=$("newPlayerUsername").value.trim(),displayName=$("newPlayerDisplayName").value.trim()||username,password=$("newPlayerPassword").value||"";$("createPlayerError").textContent="";try{const d=await api("/players",{method:"POST",body:JSON.stringify({username,displayName,password})});active=d.player;saveLocal();show("createPlayerModal",false);await refresh();openPage("dashboard")}catch(e){$("createPlayerError").textContent=e.message}}
async function saveScrim(){if(!active)return alert("Create/select a player first.");const b={playerId:active.id,mode:$("scrimModeSelect").value,kit:$("scrimKitSelect").value,map:$("scrimMap").value,scoreFor:$("scrimScoreFor").value,scoreAgainst:$("scrimScoreAgainst").value,opponents:$("scrimOpponents").value,kills:$("scrimKills").value,deaths:$("scrimDeaths").value,bedsDestroyed:$("scrimBedsDestroyed").value,opponentRP:$("scrimOpponentRP").value};try{const d=await api("/matches/scrim",{method:"POST",body:JSON.stringify(b)});show("scrimModal",false);await refresh();openResult(d)}catch(e){alert(e.message)}}
async function saveLG(){if(!active)return alert("Create/select a player first.");try{const d=await api("/matches/lg",{method:"POST",body:JSON.stringify({playerId:active.id,opponent:$("lateOpponent").value,scoreFor:$("latePlayerScore").value,scoreAgainst:$("lateOpponentScore").value})});show("lateGameModal",false);await refresh();openResult(d)}catch(e){alert(e.message)}}
function openResult(d){show("rpResultModal");text("rpResultValue",(d.breakdown.final>=0?"+":"")+d.breakdown.final);text("rpResultTitle",d.match?.type==="LG"?"Late Game Rating":"Scrim Rating");$("rpBreakdownRows").innerHTML=Object.entries(d.breakdown).map(([k,v])=>`<div class="match-row"><span>${k}</span><b>${v}</b></div>`).join("")}
document.addEventListener("click",e=>{const page=e.target.closest(".nav-button")?.dataset.page;if(page)openPage(page);const modal=e.target.closest("[data-close-modal]")?.dataset.closeModal;if(modal)show(modal,false)});
$("newPlayerBtn")?.addEventListener("click",()=>show("createPlayerModal"));$("quickAddBtn")?.addEventListener("click",()=>show("scrimModal"));$("dashboardAddMatchBtn")?.addEventListener("click",()=>show("scrimModal"));$("addScrimBtn")?.addEventListener("click",()=>show("scrimModal"));$("openLateGameBtn")?.addEventListener("click",()=>show("lateGameModal"));$("quickAddLGBtn")?.addEventListener("click",()=>show("lateGameModal"));$("playersCreateBtn")?.addEventListener("click",()=>show("createPlayerModal"));$("createPlayerSubmit")?.addEventListener("click",createPlayer);$("saveScrimBtn")?.addEventListener("click",saveScrim);$("saveLateGameBtn")?.addEventListener("click",saveLG);$("activePlayerSelect")?.addEventListener("change",e=>window.selectPlayer(e.target.value));
refresh().catch(e=>{text("serverStatus","OFFLINE");console.error(e)});
